version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: Env_Variables/Install_Depedencies
      timeout: 300
      runas: root
    - location: Env_Variables/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: Env_Variables/stop_server
      timeout: 300
      runas: root